# Generated by Django 5.0.6 on 2024-06-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='noticias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=500)),
                ('descripcion', models.TextField()),
                ('autor', models.CharField(max_length=500)),
                ('fecha_publicacion', models.CharField(max_length=500)),
                ('activo', models.BooleanField()),
            ],
        ),
    ]
